keyStrings = {
    'lang':'ქართული',
    'alhabet':'აბგდევზთიკლმნოპჟრსტუფქღყშჩცძწჭხჯჰ',
    'Channel list. Category: ':'არხების ჩამონათვალი. კატეგორია: ',
    'EPG':'პროგრამა',
    'Category':'კატეგორია',
    'Actions':'ქმედება',
    'Description':'ჩამონაწერი',
    'Open in PiP':'გახსნა PiP',
    'Move channel up':'არხის გადატანა ზემოთ',
    'Move channel down':'არხის გდატანა ქვემოთ',
    'Delete channel':'არხის წაშლა',
    'Add channel to category':'არხის დამატება კატეგორიაში',
    'Add channel to favorites':'არხის დამატება რჩეულებში',
    'Channel parental control':'პირადი კონტროლი არხების',
    'Channel is not available!!!':'არხი მიუწვდომელია!!!',
    'min':'წუთი',
    'Channel ':'არხი ',
    ' added to category ':' დამატებულია კატეგორიაში ',
    ' added to favorites':' დამატებულია რჩეულებში ',
    'Favorites':'რჩეულები',
    'Select category to add channel':'კატეგორიის არჩევა არხების დასამატებლად',
    'Enter parental code':'შეიყვანეთ ქარხნული კოდი',
    'Wrong parental code !!!':'არასწორი ქარხნული კოდი !!!',
    '<br>Up<br>':'<br>ზემოთ<br>',
    '<br>Delete':'<br>წაშლა',
    '<br>Add<br>to favorites':'<br>დამატება<br>რჩეულებში',
    '<br>Add<br>to category':'<br>დამატება<br>რჩეულებში',
    '<br>Parental<br>Control':'<br>პირადი<br>კონტროლი',
    '<br>Down':'<br>ქვემოთ',
    'Close':'დახურვა',
    'Edit category name':'კატეგორიის რედაქტირება',
    'Category %1 already exists!':'კატეგორია %1 უკვე არსებობს!',
    'Enter name for new category':'შეცვალეთ სახელწოდება ახალი კატეგორიის',
    '<br>More...<br>':'<br>კიდევ...<br>',
    '<br>Rename':'<br>შეცვლა',
    '<br>Copy<br>category':'<br>კოპირება<br>კატეგორიის',
    '<br>Back<br>':'<br>უკან<br>',
    '<br>Create<br>category':'<br>შექმნა<br>კატეგორიის',
    'Category selection':'შერჩევა არხების კატეგორიაში',
    'Menu':'მენიუ',
    'Channel list':'არხების ჩამონათვალი',
    'Move category up':'გადატანა კატეგორიის ზემოთ',
    'Move category down':'გადატანა კატეგორიის ქვემოთ',
    'Create category':'კატეგორიის შექმნა',
    'Rename category':'კატეგორიის შეცვლა',
    'Copy category':'კატეგორიის კოპირება',
    'Delete category':'კატეგორიის წაშლა',
    'Su Mo Tu We Th Fr Sa':'კვ ორ სამ ოთხ ხუთ პარ შაბ',
    'EPG and archive. Channel: ':'პროგრამა და არქივი. არხი: ',
    'By alphabet':'ალფავიტის მიხედვით',
    'Archive. Channel: ':'არქივი. არხი: ',
    'By time':'დროის მიხედვით',
    'Player info:':'ფლეიერის ინფორმაცია:',
    'Device info:':'მოწყობილობის ისტორია:',
    '- switch:':'- გადართვა:',
    '- erase':'- წაშლა',
    '- move cursor':'- კურსორის გადატანა',
    '- return without save':'- დაბრუნება დამახსოვრების გარეშე',
    '- save':'- დამახსოვრება',
    'Return to previous channel':'წინა არხზე დაბრუნება',
    'Call PiP / PiP exchange':'გამოძახება PiP / მომწოდებლის შეცვლა PiP',
    'Info about TV program':'გადაცემის ინფორმაციის მიღება',
    'Show player menu':'ფლეიერის მენიუს გამოძახება',
    'Interface settings':'ინტერფეისის რედაქტირება',
    'Show channel selection list':'არხების გამოძახება რედაქტირება ',
    'Hide / Return':'მოვაცილოთ ინფორმაცია / დაბრუნება',
    'Exit player':'ფლეიერიდან გამოსვლა',
    'Show EPG and archive for channel':'პროგრამოს გამოძახება არხების ნახვა და არქივი',
    'Channel category selection':'კატეგორიის შერჩევა',
    'Toggle Aspect Ratio':'რეჟიმის გადართვა "ეკრანის ასპექტის თანაფარდობა" (Aspect Ratio)',
    'Toggle Zoom Mode':'გადართვა გაფართოებაზე',
    'Switch sound track':'გადართვა ხმის',
    'In live mode: <br/>':'პირდაპირი ჩართვა რეჟიმის:<br/>',
    'Channel selection by number':'ნომრების მიხედვით არხების არჩევა',
    'Timeshift: to start of TV program':'ჩართვისას: საწყისი გადაცემა',
    'Timeshift: one minute back':'ჩართვისას: ერთი წუთით უკან',
    '<br/><br/>In archive mode:<br/>':'<br/><br/>ნახვა არქივის რეჯიმში:<br/>',
    'Pause/Play':'შეჩერება/გაშვება',
    'Stop playback and return to In live mode':'გავაჩეროთ გამოსახულება და გადავიდეთ პირდაპირ რეჟიმში',
    'To start of TV program / Previous TV program':'დასაწყისი გადაცემის / წინა  გადაცემის',
    'Next TV program':'შემდეგი გადაცემის',
    'Back / Forward for 1 minute':'უკან / წინ 1 წუთით',
    'Back / Forward for 15 seconds':'უკან / წინ 15 წამით',
    'Back / Forward for 3 minutes':'უკან / წინ 3 წუთით',
    'Back / Forward for 10 minutes':'უკან / წინ 10 წუთით',
    'Show rewind window':' გადახვევის ბანერის გამოძახება',
    'Description of remote control buttons':' პულტის განმარტება',
    'Description of remote control buttons depending on the view mode':'პულტის ღილაკების განმარტება ყურების დროს',
    'Set parental code':'მიმართეთ ქარხნულ კოდს',
    'Repeat parental code':'გაიმეორედ ქარხნული კოდი',
    'Show list of channel archive records':'არხის არქივის ჩანაწერების სიის ჩვენება',
    'Show list of channel archive records without duplication':'არხის არქივის ჩანაწერების სიის ჩვენება დუბლირების გარეშე',
    'Show Media Library':'მედია ბიბლიოთეკის ჩვენება',
    'Rewind':'გადახვევა',
    'Close PiP':'დახურვა PiP',
    'Parental control':'ქარხნული კოდი',
    'Change provider':'პროვაიდერის შეცვლა',
    'Change provider - you can change the provider, and it will be remembered at the next start of player!':'პროვაიდერის შეცვლა - შეგიძლიათ შეცვალოთ პროვაიდერი და ის დაიმახსოვროს ფლეიერის შემდეგ დაწყებაზე ',
    'Restart player':'ფლეიერის გადატვირთვა',
    // 'Restart player - after changing provider settings (as example)':'ფლეიერის გადატვირთვა - მაგალითად როცა პროვაიდერი შეიცვლება ',
    'Description of remote control buttons':'პულტის ღილაკების განმარტება',
    'About':'ინფორმაცია',
    'Player and device info':'ინფორმაცია ფლეიერის და მოწყობილობის',
    'Donate <div class="btn" style="background-color:orange;">donate</div>':'პროექტის დახმარება <div class="btn" style="background-color:orange;">donate</div>',
    'Voluntary donation for the development of project':'ნებაყოფლობით დახმარება პროექტის განვითარებისთვის',
    'Settings saved':'პარამეტრების შენახვა',
    'no':'არა',
    'yes':'კი',
    'Records':'ჩაწერა',
    'Previous':'წინა',
    'Info':'იფორმაცია',
    'Not reduce video when showing the list (bugfix)':'ნუ შეამცირებთ ვიდეოს ჩამონათვალს სიის დროს (bugfix)',
    'Black screen while switching the channel':'შავი ეკრანი არხის გადართვის დროს',
    'PiP window size':'ჩარჩოს ზომა PiP',
    'small':'პატარა',
    'medium':'საშვალო',
    'large':'დიდი',
    'PiP window position':'ჩარჩოს პოზიცია PiP',
    'top-right':'მარჯვნივ-ზემოთ',
    'bottom-right':'მარჯვნივ ქვემოთ',
    'left-bottom':'მარცხნივ ქვემოთ',
    'top-left':'მარცხნივ ზემოთ',
    'Number of rows in lists':'ხაზების რაოდენობა სიებში',
    'Distance between lines in lists':'დაშორება სიებში ხაზებს შორის',
    'Font type':'შრიფტის ფორმატი',
    'volume':'ხმა',
    'paging':'ფრიალი',
    'Nothing':'არაფერი',
    'Exit':'გამოსვლა',
    'Joystick':'ჯოისტიკი',
    'Button %1 function when viewing':'ღილაკის ფუნქცია %1 ყურების დროს',
    'Button function %1 when viewing archive':'ღილაკის ფუნქცია %1 არქივის ყურების დროს',
    'Channels':'არხები',
    'Remote (color buttons N/A)':'პულტი უფერადო ღილაკებით',
    'Remote (number buttons N/A)':'პულტი ციფრული ღილაკების გარეშე',
    'Timezone':'დროის სარტყელი',
    'Sleep timer':'ძილის ტაიმერი',
    'off':'გამორთვა',
    '30 minutes':'30 წუთი',
    '1 hour':'1 საათი',
    '2 hours':'2 საათი',
    'Infobar display timeout, s':'საინფორმაციო ზოლის ჩვენების დრო ამოიწურა, с',
    '"Sliding" infobar':'"გამავალი" ინფობარი',
    'Interface transparency':'ინტერფეისის გამჭვირვალობა',
    'Volume step, %':'ხმის მოცულობა, %',
    'List location':'ჩამოთვალეთ ადგილმდებარეობა',
    'right':'მარჯვნივ',
    'left':'მარცხნივ',
    'Color spectrum':'ფერის სპექტრი',
    'select':'არჩევა',
    'Permanent clock on screen':'მუდმივი საათი ეკრანზე',
    'Show channel number in list':'არხის ნომრის ჩვენება სიაში',
    'Show picons in channel list':'არხების სიაში ნაჩვენები პიკონები',
    'Show channel name in list':'არხის სახელის ჩვენება სიაში',
    'Show progress in channel list':'პროგრესის ჩვენება არხების სიაში',
    'Show archive availability in list':'სიაში არქივის არსებობის ჩვენება',
    'Show scrollbar in list':'გადახვევის ზოლის ჩვენება სიაში',
    'Preview in channel list':'გადახედვა არხების სიაში',
    'always':'ყოველთვის',
    'on ':'ავტორი ',
    'Number of next TV programs in channel list':'შემდეგი პროგრამების რაოდენობა არხების სიაში',
    'Channel list editing style':'სიის რედაქტირების სტილი',
    'All categories':'ყველა კატეგორია',
    '"Favorites"':'"რჩეულები"',
    'Editor':'რედაქტირება',
    'built-in':'ჩაშენებული',
    'native':'ქარხნული',
    'HDMI-CEC support (on/off from TV)':'HDMI-СEC მხარდაჭერა (ჩართვა/გამორთვა ტელევიზორიდან)',
    'Type of player for streaming':'ფლეიერის ტიპი დაკვრისთვის',
    'Autostart of player':'ფლეიერი ავტომატიურად  იწყებს ჩართვას',
    'Buffer Size, s':'ბუფერის ზომა, с',
    'Choose from':'ვარიანტები',
    'Settings':'პარამეტრები',
    'Change value':'მნიშვნელობის შეცვლა',
    'Save Settings':'პარამეტრების დამახსოვრება',
    'To begining':'დასაწყისში',
    'Live':'პირდაპირი ეთერი',
    ' m ':' წუთი ',
    ' s':' წამი',
    '1 minute':'1 წუთი',
    '10 Seconds':'10 წამი',
    'Go to':'გადასვლა',
    'Archive - begin':'არქივი - თავიდან დაწყება გადაცემის',
    'Pause':'შეჩერება',
    'Play':'ჩართვა',
    'Shutdown after %1 seconds<br/><br/>Cancel - any action':'გამორთვა შემდეგ %1 წამი<br/><br/>უარყოფა - ყველანაირი ქმედება',
    'Do you want to exit player?':'თქვენ გინდათ გამოხვიდეთ ფლეიერიდან?',
    'Color':'ფერი',
    'Saturation':'სიმკვეთრე',
    'Yellow':'ყვითელი',
    'Green':'მწვანე',
    'Blue':'ლურჯი',
    'Set':'დაყენება',
    'Restart stream':'რესტარტი პარამეტრების',
    'Favorites':'რჩეულები',
    'All':'ყველა',
    '<br/>Processing the channel list...':'<br/>მიმდინარეობს არხების სიის დამუშავება...',
    '<br/>Start playback...':'<br/>დაწყება ჩართვა...',
    '<br/>Channel list not received !!!':'<br/>არხების სია არ არის მიღებული!!!',
    'Channel list not received !!!<br/><br/>Enter the provider data and restart the player !!!<br/><br/>':' სია არ არის მიღებული არხების!!!<br/><br/>შეიყვანეთ თქვენი პროვაიდერის დეტალები და გადატვირთეთ პლერი!!!<br/><br/>',
    'Error getting channel list !!!':'შეცდომა არხების სიის მიღებისას!!!',
    'system':'სისტემური',
    'Choose provider':'აირჩიეთ პროვაიდერი',
    '<br>Rewind<br>':'<br>გადახვევა<br>',
    '<br>Menu':'<br>მენიუ',
    '<br>Pause<br>':'<br>პაუზა<br>',
    '<br>Toggle<br>sound track':'<br>გადართვა<br>ხმის ბილიკის',
    '<br>Live':'<br>პირდაპირი ეთერი',
    '<br>Previous<br>channel':'<br>მანამდე<br>канал',
    '<br/><b>Failed to load provider script !!!</b>':'<br/><b>პროვაიდერის სკრიპტის ჩატვირთვა ვერ მოხერხდა!!!</b>',
    '<br/>Loading provider %1 script ...':'<br/>მიმდინარეობს პროვაიდერის სკრიპტის ჩატვირთვა %1 ...',
    '<br/>Loading settings...':'<br/>პარამეტრების ჩატვირთვა...',
    '<br/>Loading channel list...':'<br/>არხების ჩამონათვალის ჩატვირთვა...',
    'Choose language':'აირჩიეთ ენა',
    'Change interface language':'ენის შეცვლა',
    'Aspect':'ასპექტი',
    'Audio':'ხმის ბილიკი',
    'Stalker portals':'სტალკერის პორტალები',
    'm3u-m3u8 playlists':'m3u-m3u8 დასაკრავი სიები',
    '<br/>Loading STB...':'<br/>იტვირთება STB...',
    '<br/>Setup STB...':'<br/>პარამეტრები STB...',
    'Save settings to storage':'ჩაწერეთ პარამეტრები ფლეშკაზე',
    'Load settings from storage':'პარამეტრების აღდგენა ფლეშ დრაივიდან',
    'Download':'გადმოწერა',
    'Skip this version':'გაატარე დაიკიდე ეს ვერსია',
    'Volume control':'ხმის რეგულირება',
    'Long button presses':'ღილაკზე ხანგრძლივი დაჭერა',
    'Download new version Android App':'ჩამოტვირთეთ ანდროიდის ახალი ვერსია',
    'To access you must enter url, username and password!':'შესასვლელად თქვენ უნდა შეიყვანოთ თქვენი მისამართი, შესვლა და პაროლი!',
    'Failed to load channel list!':'არხების სიის ჩატვირთვა ვერ მოხერხდა!',
    'Year':'წელი',
    'Duration':'ხანგრძლივობა',
    'Genre':'ჟანრი',
    'Country':'ქვეყანა',
    'Director':'რეჯისორი',
    'Actors':'როლებში',
    'Release date':'გამოშვების თარიღი',
    'Rating':'რეიტინგი',
    'Season':'სეზონი',
    'Episodes':'ეპიზოდების რაოდენობა',
    'VOD':'ფილმები და ვიდეო',
    'TV series':'სერიალები',
    'Episode':'ეპიზოდები',
    'Download! Wait ...':'ჩატვირთვა! მოიცადეთ ...',
    'Server':'სერვერი',
    'URL':'მისამართი',
    'Username':'სახელი',
    'Password':'პაროლი',
    'Stream type':'ნაკადის ტიპი',
    'Account info':'გამოწერის ინფორმაცია',
    'Select server number from 1 to 6 to save data':'აირჩიეთ სერვერის ნომერი 1-დან 6-მდე მონაცემების შესანახად',
    ' (after changing, restart player)':' (ცვლილების შემდეგ საჭიროა ფლეიერის გადატვირთვა)',
    ' (after changing, switch the channel!)':' (ცვლილების შემდეგ შეცვალეთ არხი!)',
    'Enter URL of server':'სერვერის მისამართის რედაქტირება',
    'Enter username':'მიმდინარეობს შესვლის რედაქტირება',
    'Enter password':'პაროლის რედაქტირება',
    'Select stream type':'აირჩიეთ ნაკადის ტიპი',
    '??? No channel name':'??? არხის სახელი არ არის',
    'Playlist URL':'დასაკრავი სიის მისამართი',
    'Archive hours':'არქივის საათების რაოდენობა',
    'Enter playlist URL':'დასაკრავი სიის მისამართის შეყვანა',
    'Enter playlist archive hours':'დასაკრავი სიისთვის არქივის საათების რაოდენობის შეყვანა',
    'show on-screen keyboard':'ეკრანის კლავიატურის გამოძახება',
    'Sleep without leaving player':'დაიძინე ფლეიერის დატოვების გარეშე',
    'PiP is not available!':'PiP მიუწვდომელია!',
    'NORMAL':'ჩვეულებრივი',
    'ENLARGE':'მომატება',
    'MAKE_WIDER':'სიგანის გაზრდა',
    'NON_LINEAR_STRETCH':'არაწრფივი გაჭიმვა',
    'NON_LINEAR_STRETCH_TO_FULL_SCREEN':'არაწრფივი გაჭიმვა სრულ ეკრანზე',
    'MAKE_TALLER':'სიმაღლის გაზრდა',
    'CUT_EDGES':'მოჭრილი კიდეები',
    'FULL_SCREEN':'მთლიანი ეკრანი',
    'STRETCH_TO_FULL_SCREEN':'გაჭიმვა მთელ ეკრანზე',
    'Background color':'ფონის ფერი',
    'Brightness':'განათება',
    '3 hours':'3 საათი',
    'Restart stream / Live':'გადატვირთეთ ნაკადი / პირდაპირი ტრანსლიაცია',
    '- keyboard': '- კლავიატურა',
    'Media':'მედია',
    'String for search':'ძიების სტრიქონი',
    // 'Playlist Name':'დასაკრავი სიის სახელი',
    // 'Enter playlist Name':'დასაკრავი სიის სახელის შეყვანა',
    'Media Library URL':'მედია ბიბლიოთეკის მისამართი',
    'Enter Media Library URL':'ბიბლიოთეკის მისამართის შეყვანა',
    'Playlist':'დასაკრავი სია',
    'Select playlist':'შეარჩიეთ დასაკრავი სია',
    'Edit':'რედაქტირება',
    'Load':'ჩამოტვირთვა',
    'Edit playlist data':'დასაკრავი სიის მონაცემების რედაქტირება',
    'Select portal':'აირჩიეთ პორტალი',
    'Portal Name':'პორტალის სახელი',
    'Enter Portal Name':'შეიყვანეთ პორტალის სახელი',
    'Edit portal data':'პორტალის მონაცემების რედაქტირება',
    'without':'გარეშე',
    'Settings STB':'მოწყობილობის პარამეტრები',
    'Soft audio render':'აუდიოს გაშიფვრა პროგრამულად',
    'Long press horizontal arrows for volume control':'ხმის კონტროლი ჰორიზონტალური ისრებით',
    'Yes':'კი',
    'Back':'უკან',
    'Show providers?':'პროვაიდერების შერჩევის ჩვენება?',
    'Hide providers?':'პროვაიდერის შერჩევის დამალვა?',
    'Show provider settings?':'პროვაიდერის პარამეტრების ჩვენება?',
    'Hide provider settings?':'პროვაიდერის პარამეტრების დამალვა?',
    'Clear all settings?':'გაასუფთავეთ ყველა პარამეტრი?',
    'Timer':'ტაიმერი',
    'Set timer?':'დააყენეთ ტაიმერი?',
    'Remove timer?':'ტაიმერის წაშლა?',
    'Timer: switch to channel?':'Таймер:არხზე გადართვა ?',
    ' (if archive exists)':' (თუ არსებობს არხის არქივი)',
    'Preffered audio track':'სასურველი აუდიო ჩანაწერი',
    'Information':'ინფორმაცია',
    'Lists settings':'სიის პარამეტრები',
    'Channel list settings':'არხების სიის პარამეტრები',
    'Buttons settings':'დისტანციური მართვის ღილაკის პარამეტრები',
    'Subtitle':'სუბტიტრები',
    'Switch subtitle':'სუბტიტრების გადართვა',
    'Off':'გამორთვა',
    'Not found':'არცერთი',
    'History of watched movies':'დათვალიერების ისტორია',
    'Continue watching?':'განაგრძეთ დათვალიერება?',
    'Add to favorites':'რჩეულებში დამატება',
    'Delete':'წაშლა',
    'Info about current stream':'ინფორმაცია მიმდინარე ნაკადის შესახებ',
    'Stop':'შეჩერება',
    'Playlist file':'დასაკრავი სიის ფაილი',
    'Select playlist file':'დასაკრავი სიის ფაილის შერჩევა',
    'Graphical indication':'გრაფიკული ჩვენება',
    'Background color of selected item':'ფონის ფერის შერჩევა',
    'Default':'ნაგულისხმევი',
    'Not supported!':'არ არის მხარდაჭერილი!',
    'Menu items settings':'მენიუს ელემენტების დაყენება',
    'Select menu items':'აირჩიეთ მენიუს ელემენტები',
    'Protect Adult Channels':'"ზრდასრული" არხების დაცვა',
    'Protect Settings':'პარამეტრების დაცვა',
    'Protect Change Provider':'პროვაიდერის შეცვლასთან დაკავშირებული დაცვა',
    'Infobar settings':'ინფობარის პარამეტრები',
    'Show when switching':'ჩვენება გადართვისას',
    'Show when changing program':'პროგრამის შეცვლისას ჩვენება',
    'Show when rewind':'ჩვენება უკან გადახვევისას',
    'Archive. Category: ':'არქივი. კატეგორია: ',
    'Sort channels':'დახარისხება',
    '"As Is"':'"როგორც არის"',
    'Load playlist':'ჩამოტვირთეთ დასაკრავი სია',
    ' (after changing, load playlist)':' (ცვლილების შემდეგ ჩატვირთეთ დასაკრავი სია)',
    'Statistics of current stream':'მიმდინარე ნაკადის სტატისტიკა',
    'Search':'ძიება',
// 14.6
    'Behavior of %1/%2 buttons in lists':'არჩევა ღილაკების %1/%2 სიებში',
    'begin/end':'დაწყება/დამთავრება',
    'Position shift -10 seconds after pause':'პოზიციის შეცვლა -10 წამით პაუზის შემდეგ',
    'Remember previous channels':'დაიმახსოვრე წინა არხები',
    'History in Media Library':'დათვალიერების ისტორია მედია ბიბლიოთეკაში',
// 5.11
    'Manage settings':'პარამეტრების მართვა',
    'Save settings':'პარამეტრების შენახვა',
    'Load settings':'პარამეტრების ჩატვირთვა',
    'Clear settings':'პარამეტრების გასუფთავება',
    'Send settings':'პარამეტრების გაგზავნა სერვერზე',
    'Settings sended!':'პარამეტრები გაიგზავნა სერვერზე!',
    'For download settings file open':'პარამეტრების ფაილის ჩამოსატვირთად გახსენით',
    'and enter code':'და შეიყვანეთ კოდი',
    'or scan':'ან სკანირება',
    'Send request':'მოთხოვნის გაგზავნა სერვერზე',
    'Request sended!':'მოთხოვნა გაიგზავნა სერვერზე!',
    'For upload settings file open':'პარამეტრების ფაილის ჩამოსატვირთად გახსენით',
    'Enter Provider Code':'პროვაიდერის კოდის შეყვანა',
    'Error Code!':'კოდის შეცდომა!!!',
    'For enter value open':'მნიშვნელობის შესაყვანად გახსენით',
    'First Run Setup':'პირველად დაყენება',
    'Enter Provider Code on PC or Phone':'შეიყვანეთ თქვენი პროვაიდერის კოდი თქვენს კომპიუტერში ან ტელეფონში',
    'Manual setup':'ხელით დაყენება',
    'Access settings':'წვდომა პარამეტრებზე',
// 26.1
    'Script':'სცენარი',
    'Producer':'პროდიუსერი',
    'Operator':'ოპერატორი',
    'Composer':'კომპოზიტორი',
    'Artist':'მხატვარი',
    'Installation':'მონტაჟი',
    'Budget':'ბიუჯეტი',
    'Audience':'აუდიტორია',
    'Premiere world':'მსოფლიო პრემიერა',
    'Display settings':'ჩვენების პარამეტრები',
    'Age':'ასაკი',
    'Sort':'დახარისხება',
    'by name':'სახელით',
    'by adding':'დამატებით',
    'Order':'შეკვეთა',
    'asc':'ასაკი',
    'desc':'მცირდება',
    'Language':'ena',
    'Quality':'ხარისხი',
    'Show program name':'სათაურის ჩვენება',
    'Show description':'გადაცემის აღწერილობის ჩვენება',
    'transparent':'გამჭვირვალე',
// 23.3
    'Rewind step by buttons %1/%2':'გადახვევა ეტაპობრივად ღილაკებით %1/%2',
// 10.2
    'Show thumbnails':'ესკიზების ჩვენება',
// 29.6
    'Show program name in previous channels':'შოუს სათაურის ჩვენება წინა არხებზე',
    // 'Delete playlist':'დასაკრავი სიის წაშლა',
    'Save channel list':'შეინახეთ არხების სია',
    'Use local EPG':'გამოიყენეთ ადგილობრივი EPG',
    'Load EPG from playlist':'ჩატვირთვა EPG დასაკრავი სიიდან',
    'Local EPG':'ადგილობრივი EPG',
    'Edit EPG data':'წყაროს მონაცემები EPG',
    'Name':'სახელი',
    'Enter Name':'სახელის შეყვანა',
    'Enter URL':'მისამართის შეყვანა',
    'Update period, hours':'განახლების პერიოდი, საათები',
    'Enter update period, hours':'განახლების პერიოდის შესვლა, საათები',
    'Clear':'გაწმენდა',
}